max_tokens: 77
image_res: 224
batch_size: 8
return_index: false
use_test_transform: false

coco_file: 'data/pretrain/coco_pretrain.json'
coco_image_root: 'images/coco'

image_key:   "image"
caption_key: "caption"
dataset_key: "dataset"

max_words: 40
