max_tokens: 77
image_res: 224
batch_size: 8
return_index: false
use_test_transform: false

flickr30k_file: 'data/pretrain/flickr30k_pretrain.json'
flickr30k_image_root: 'images/flickr30k'

image_key:   "image"
caption_key: "caption"
dataset_key: "dataset"

max_words: 40
